changelog:
  exclude:
    labels:
      - ignore-for-release
      - tagpr
    authors:
      - renovate
  categories:
    - title: Fixed
      labels:
        - bug
    - title: Added
      labels:
        - enhancement
    - title: Changed
      labels:
        - '*'
