on:
  push:
    tags:
      - '*'

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Publish to Visual Studio Marketplace
          - run: npm install
          - run: "npm publish -p ${{ secrets.VS_MARKETPLACE_TOKEN }}"
